#!/bin/bash

TOGGLE=$HOME/dotfiles/scripts/.toggle

if [ ! -e $TOGGLE ]; then
	touch $TOGGLE
	nitrogen --set-zoom-fill --save $HOME/Pictures/debian.png
else
	rm $TOGGLE
	nitrogen --set-zoom-fill --save $HOME/Pictures/kyuute_dress_girl.png

fi
